spring.datasource.url=jdbc:sqlite:/var/www/andreyferraz.com.br/public_html/gestao/gestao.db
spring.sql.init.mode=never
server.forward-headers-strategy=framework
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=30MB
upload.dir=/var/www/andreyferraz.com.br/public_html/gestao/uploads