spring.application.name=gestao
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
app.bootstrap.admin.password=${APP_BOOTSTRAP_ADMIN_PASSWORD:}
server.servlet.context-path=/gestao
server.servlet.session.timeout=30m
spring.datasource.url=jdbc:sqlite:gestao.db
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=30MB
